sudo: required
services:
  - docker

before_install:
  - docker build -t hantdaniel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hantdaniel/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-582248655453"
  bucket_patch: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"